//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LB3.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerW
    {
        public int QuestionNumber { get; set; }
        public System.Guid HumanId { get; set; }
        public System.DateTime AnswerTime { get; set; }
        public string AnswerText { get; set; }
    
        public virtual Human Human { get; set; }
        public virtual QuestionW QuestionW { get; set; }
    }
}
